### ISSUE TITLE
Create unit test battery.

### ISSUE THREAD

**Issue by NovoaDev** [NovoaDev/Dependency-Graph-BCExt#16]
1. **Create codeunit facade for the following calls:**
codeunit 80807 GenerateTables_ANJ
Generate <br>
codeunit 80805 GenerateExtensionTable_ANJ
CleanExtensionsTable 
Generate <br>
codeunit 80806 NumberSequenceMgmt_ANJ
GetNextNo <br>
codeunit 80804 GenerateFigure_ANJ
Generate <br>
codeunit 80809 MarkdownMgmt_ANJ
GenerateGraph <br>
codeunit 80808 GenerateRelationsTable_ANJ
CleanRelationsTable 
Generate <br>

2. **Implement Interface:**
codeunit 80805 GenerateExtensionTable_ANJ
Mock ws (interface)

3. **Test fields:**
table 80802 Relations_ANJ
field(3; SourceAppName; Text[2048]) <br>
table 80801 Extensions_ANJ
UpdateFigure();
field(9; HasStartRelationships; Boolean)
field(10; HasRelationships; Boolean)

**Comment by anovoa-ldr** [comment]
After analysis, it is separated into four test CUs to cover the minimum necessary, two are already created in this ticket and additional tickets will be created with the missing CUs.
