### ISSUE TITLE
Update config files2

### ISSUE THREAD

**Issue by NovoaDev** [NovoaDev/Dependency-Graph-BCExt#41]
Las 2 thinks of #37 moved to this new issue.
- [x] Update config files for System and Project. two levels
- [ ] AlDoc.
- [x] Update Issue template - Yaml
- [x] Update New Features template - Yaml
- [ ] Update PR template - Yaml
- [ ] Update Sponsoreships
- [x] Update test extension
- [x] Create contributing.md
- [x] Deactivate repository actions
- [x] Set UpdateGitHubGoSystemFilesSchedule

**Comment by anovoa-ldr** [comment]
[Microsoft_Library Assert_23.4.15643.16876.zip](https://github.com/NovoaDev/Dependency-Graph-BCExt/files/14473660/Microsoft_Library.Assert_23.4.15643.16876.zip)

Test toolkit symbols for Docker problems.

**Comment by NovoaDev** [comment]
For some strange reason if I downloaded the symbols from the sandbox I downloaded the testtoolkit apps but could not find the CU of permisions. I had to create a docker and download the symbols to add the namespaces and test.
